---
- hosts: localhost
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: docker install
      yum:
        name: docker
        state: present

    - name: docker up
      service:
        name: docker
        state: started
