---
- hosts: localhost 
  become: true
  tasks:
    - name: user creation
      user:
        name: prasanta
        state: present

    - name: docker install
      yum:
        name: docker
        state: present

    - name: docker up
      service:
        name: docker
        state: started
    - name: dockerfile
      docker_image:
        name: ubuntu
        path: /Jenkins_test/
    - name: docker container
      docker_container:
        name: ubuntu container
        image: ubuntu
        state: started
        ports:
          - "82:80"
    

    
     

