---
- hosts: localhost 
  become: true
  vars:
    packages:
      - git
      - python
      - wget
      - java-17
      - docker
  tasks:
    - name: isntall package
      yum:
        name: "{{item}}"
        state: present
      with_items: "{{packages}}"
    - name: jenkins installation
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: add key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present
    - name: jenkins install
      yum:
        name: jenkins
        state: present
    - name: jenkins start 
      systemd:
        name: jenkins
        state: started
    - name: user creation
      user:
        name: prasanta
        state: present

    - name: docker install
      yum:
        name: docker
        state: present

    - name: docker up
      service:
        name: docker
        state: started
    - name: docker command execute
      command: docker build -t containern /Jenkins_test/.

    - name: port
      command:  docker run -d -p 8080:80 --name nginxma containern
    

    
     

