---
- hosts: localhost 
  become: true
  tasks:
    - name: user creation
      user:
        name: prasanta
        state: present

    - name: docker install
      yum:
        name: docker
        state: present

    - name: docker up
      service:
        name: docker
        state: started
     

