---
- hosts: localhost 
  tasks:
    - name: user creation
      user:
        name: prasantaa
        state: present
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
  tasks:
    - name: httpd start
      service:
        name: httpd
        state: start

