---
- hosts: localhost 
  become: true
  tasks:
    - name: user creation
      user:
        name: prasanta
        state: present

    - name: docker install
      yum:
        name: docker
        state: present

    - name: docker up
      service:
        name: docker
        state: started
    - name: docker command execute
      command: sudo docker build -t containern .

    - name: port
      command: sudo docker run -d -p 8080:80 --name nginxma containern
    

    
     

