---
- hosts: localhost 
  tasks:
    - name: user creation
      user:
        name: prasanta
        state: present
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

